export const services = [
    {name:'Product Launch', link: '/service/product-launch', imgUrl: '/images/services/product-launch.png', content: "We bring brands to life through impactful, on-ground experiences that engage, excite, and convert. Our brand activation services are designed to generate buzz and build real emotional connections with your target audience. From product sampling and interactive kiosks to mall activations and pop-up events, we ensure your brand doesn’t just get noticed — it gets remembered. With 6+ years in the industry, we've activated campaigns for major clients like HDFC Bank, Kenstar, and Finolex. From concept to execution, we manage creatives, logistics, staffing, and on-site engagement to deliver seamless, high-impact experiences.", id:'e5971c3b-2642-474f-b958-559ca30ba213'},

    {name:'Carnival Day', link: '/service/carnival-day', imgUrl: '/images/services/carnival.png', content: "Celebrate culture, community, and connection with well-managed festival events. From Diwali melas and Holi parties to Navratri nights and Christmas carnivals — we handle decoration, entertainment, logistics, crowd management, and security. Whether it’s for corporate teams, residential societies, or public spaces, we make sure every celebration is colorful, safe, and full of life.",id:'48e40b07-529c-4127-83f7-ea88fe57006b'},

    {name:'exhibition', link: '/service/exhibition', imgUrl: '/images/services/exhibition.png', content:"Make your mark at trade shows and expos with impactful exhibition setups. From stall design and fabrication to branding and interactive displays, we offer complete solutions that attract, engage, and impress. Our team ensures your brand stands out amidst the crowd, creating spaces that tell your story and invite interaction. Whether you’re showcasing products or networking with clients, we’ll help you do it with style and substance.",id:'96ac623c-cd1e-4d09-83b0-4b3cae2d0547'},

    {name:'Board Branding', link: '/service/board-branding', imgUrl: '/images/services/board-boarding.png', content: "Transform your retail space into a powerful brand experience. We specialize in in-store branding, window displays, product signage, shelf designs, and more — all aimed at attracting customers and enhancing brand visibility. Our solutions are both creative and strategic, ensuring your store leaves a lasting impression and drives footfall. Whether it’s a new store launch or a seasonal promotion, we make sure your retail branding stands out.",id:'71a08ebf-c093-4e0d-990e-cd5344b9201c'},

    {name:'Road Show', link: '/service/road-show', imgUrl: '/images/services/road-show.png', content: "Expand your brand’s reach with attention-grabbing road shows. We specialize in mobile brand promotions that travel across cities, towns, and rural markets. Using branded vans, mobile stages, and live engagement activities, we help you connect with audiences right where they are. We take care of everything — vehicle fabrication, route planning, permits, emcees, promotions, and reporting. Whether it’s a new product launch or a regional marketing campaign, our road shows are designed to leave a powerful, lasting impression.", id:'22a1bfaf-b67a-4750-bd38-252c821c38e1'},

    {name:'artist management', link: '/service/artist-management', imgUrl: '/images/services/artist-management.png', content: "We craft memorable events that capture attention and deliver value. Whether it’s a product launch, dealer meet, award night, or internal company event, we handle everything — from venue booking and stage design to branding, catering, and guest management. With years of experience and a long list of top-tier clients, we ensure flawless execution and meaningful experiences. Your goals become our blueprint as we bring together creativity, coordination, and energy to deliver events that your audience will talk about long after it ends.", id:'58a46def-68bf-414f-ac84-af8c6d74a12b'},

    {name:'conference', link:'/service/conference', imgUrl: '/images/services/conference.jpg', content: "Make your corporate conference seamless and impactful with our end-to-end planning services. We manage every detail — from venue selection, AV setup, and branding to registration, speaker coordination, and delegate engagement. With experience organizing professional events for banks, cement giants, and global firms, we bring structure and creativity to the table. Whether it’s an industry seminar or an internal strategy meet, we ensure a professional, tech-enabled environment that reflects your brand’s credibility.", id:'3473ab6b-173e-4f6f-9c8e-0d5e8b09d085'},

    {name:'Wall Painting', link:'/service/wall-painting', imgUrl: '/images/services/wall-painting.jpg', content:"Transform blank walls into vibrant, eye-catching brand canvases. Our wall painting services combine art and advertising to make your message stand out in public spaces. Ideal for long-term promotions in high-traffic zones, these murals are not just beautiful — they’re effective brand statements. We handle permissions, design, execution, and quality control to ensure durability and visual appeal. Whether it’s rural campaigns or urban branding, we bring color to your communication.", id:'a99bd94f-581d-4f0b-b2cc-9b500c711718'},


    {name:'Concert', link:'/service/concert', imgUrl: '/images/services/concert.jpg', content:"We create unforgettable musical experiences with expert planning and production for concerts and music events. From artist booking and stage setup to crowd control, sound, lighting, and security — we manage it all. Whether it’s a small venue gig or a large open-ground concert, we ensure smooth execution and maximum entertainment value. Partner with us to deliver energetic, safe, and crowd-pleasing live music events.", id:'cb42f076-0119-4e0b-b05c-950f450469d8'},

    {name:'Bus, Auto & E-Rickshaw Branding', link:'/service/bus-auto-rickshaw-branding', imgUrl: '/images/services/e-rikshaw.jpg', content:"Take your brand to the streets with high-visibility transit advertising. We design and execute branding for buses, autos, and e-rickshaws — offering unmatched reach across urban and rural markets. It’s cost-effective, mobile, and constantly in motion, making it perfect for mass awareness. From artwork design to printing and application, we handle the entire process with precision and quality control.", id:'4216b83b-3fd9-4ca2-a14d-b2e1375736b3'},

    {name:'Decoration', link:'/service/decoration', imgUrl: '/images/services/decoration.jpg', content:"Set the tone with stunning, theme-based decoration for any event. Be it corporate branding, festive flair, or elegant elegance — we design and execute setups that transform your space. From floral arrangements to backdrops, entrance arches to table decor, every detail is thoughtfully crafted. We blend creativity and quality to deliver décor that impresses and elevates your event experience.", id:'63fd73ad-5c44-4b77-ba3b-fec0f568f25e'},

    // {name:' Options', link:'/service/entertainment-options', imgUrl: '/images/services/dummy.jpg', content:"Add excitement to your events with our curated entertainment services. From live bands, DJs, and celebrity appearances to folk dancers, magicians, and stunt shows — we offer a wide range of options to suit your theme and audience. With a network of trusted performers and professional production support, we deliver high-energy experiences that keep your crowd engaged and entertained.", id:'2e61bdd7-1452-4cd5-84c7-ceac2180823d'},

    {name:'Games & Entertainment', link:'/service/games-entertainment', imgUrl: '/images/services/games.jpeg', content:"Add excitement and energy to your events with our curated entertainment and gaming experiences. From live bands, DJs, celebrity appearances, and folk dancers to magicians and stunt shows — we offer a dynamic lineup of entertainment tailored to your theme and audience. To keep the fun going, we also provide a wide variety of interactive game setups including team-building activities, arcade-style stalls, VR zones, and traditional carnival games. Whether you're planning a corporate event, fair, or festival, our engaging entertainment and game zones are designed to captivate guests of all ages and create memorable moments that bring your venue to life.", id:'a2414489-fff6-438d-a09f-fe812071acc3'},

    {name:'BTL Activity', link:'/service/btl-activity', imgUrl: '/images/services/btl.jpg', content:"Boost your brand’s local visibility through impactful Below-The-Line (BTL) activations. We execute high-engagement campaigns such as society activations, door-to-door promotions, sampling drives, school programs, and more. With a strong focus on targeted communication and grassroots engagement, our BTL strategies deliver measurable results in awareness and conversion.", id:'39f2ebd8-ecbc-464b-b276-45fa6f6fb107'},
  ]